-- MySQL Script generated by MySQL Workbench
-- 11/22/16 13:17:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Dapoba_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Dapoba_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dapoba_db` DEFAULT CHARACTER SET utf8 ;
USE `Dapoba_db` ;

-- -----------------------------------------------------
-- Table `Dapoba_db`.`Printer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Printer` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Printer` (
  `Printer_ID` INT NOT NULL,
  `Printer_loc` INT NOT NULL,
  `Waiting_queue` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Printer_ID`),
  UNIQUE INDEX `Printer_ID_UNIQUE` (`Printer_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Cabinet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Cabinet` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Cabinet` (
  `cabinet_number` INT NOT NULL,
  `cabinet_state` INT NOT NULL,
  `Printer_Printer_ID` INT NOT NULL,
  PRIMARY KEY (`cabinet_number`),
  INDEX `fk_Cabinet_Printer1_idx` (`Printer_Printer_ID` ASC),
  CONSTRAINT `fk_Cabinet_Printer1`
    FOREIGN KEY (`Printer_Printer_ID`)
    REFERENCES `Dapoba_db`.`Printer` (`Printer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Order` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Order` (
  `Order_ID` INT NOT NULL,
  `Account_ID` CHAR(20) NOT NULL,
  `Filename` CHAR(50) NOT NULL,
  `print_place` INT NOT NULL,
  `page_division` INT NOT NULL,
  `color` TINYINT(1) NOT NULL,
  `File_extension` CHAR(20) NOT NULL,
  `File_list` CHAR(225) NOT NULL,
  `Cabinet_cabinet_number` INT NOT NULL,
  UNIQUE INDEX `Account_Order_ID_UNIQUE` (`Order_ID` ASC),
  INDEX `fk_Order_Account1_idx` (`Account_ID` ASC),
  INDEX `fk_Order_Cabinet1_idx` (`Cabinet_cabinet_number` ASC),
  PRIMARY KEY (`Order_ID`, `Account_ID`),
  UNIQUE INDEX `Filename_UNIQUE` (`Filename` ASC),
  CONSTRAINT `fk_Order_Account1`
    FOREIGN KEY (`Account_ID`)
    REFERENCES `Dapoba_db`.`Account` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Cabinet1`
    FOREIGN KEY (`Cabinet_cabinet_number`)
    REFERENCES `Dapoba_db`.`Cabinet` (`cabinet_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Cash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Cash` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Cash` (
  `Account_number` VARCHAR(25) NOT NULL,
  `bank_name` CHAR(20) NOT NULL,
  `account_holder_name` CHAR(20) NOT NULL,
  PRIMARY KEY (`Account_number`),
  UNIQUE INDEX `Account_number_UNIQUE` (`Account_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Credit_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Credit_Card` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Credit_Card` (
  `Credit_card_number` INT NOT NULL,
  `Credit_card_password` INT NOT NULL,
  `ExpDate` DATETIME NOT NULL,
  `Type` CHAR(20) NOT NULL,
  `Balance` INT NULL,
  `complete_signal` TINYINT(1) NULL,
  `Credit_Card_ID` VARCHAR(45) NULL,
  UNIQUE INDEX `Credit_card_number_UNIQUE` (`Credit_card_number` ASC),
  PRIMARY KEY (`Credit_card_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Mileage/Coin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Mileage/Coin` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Mileage/Coin` (
  `Deposit_ID` VARCHAR(25) NOT NULL,
  `Mileage` FLOAT NULL,
  `Coin` FLOAT NULL,
  `Cash_Account_number` VARCHAR(25) NOT NULL,
  `Credit_Card_Credit_card_number` INT NOT NULL,
  PRIMARY KEY (`Deposit_ID`),
  INDEX `fk_Mileage/Coin_Cash1_idx` (`Cash_Account_number` ASC),
  INDEX `fk_Mileage/Coin_Credit_Card1_idx` (`Credit_Card_Credit_card_number` ASC),
  CONSTRAINT `fk_Mileage/Coin_Cash1`
    FOREIGN KEY (`Cash_Account_number`)
    REFERENCES `Dapoba_db`.`Cash` (`Account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mileage/Coin_Credit_Card1`
    FOREIGN KEY (`Credit_Card_Credit_card_number`)
    REFERENCES `Dapoba_db`.`Credit_Card` (`Credit_card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Account` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Account` (
  `ID` CHAR(20) NOT NULL,
  `Name` CHAR(20) NOT NULL,
  `Birth` DATETIME NOT NULL,
  `E-mail` CHAR(40) NULL,
  `Phone_number` VARCHAR(11) NULL,
  `Password` CHAR(20) NOT NULL,
  `Authority` VARCHAR(1) NOT NULL,
  `Order_ID` INT NULL,
  `Order_Order_ID` INT NOT NULL,
  `Mileage/Coin_Deposit_ID` VARCHAR(25) NOT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `E-mail_UNIQUE` (`E-mail` ASC),
  UNIQUE INDEX `Phone_number_UNIQUE` (`Phone_number` ASC),
  UNIQUE INDEX `Order_ID_UNIQUE` (`Order_ID` ASC),
  PRIMARY KEY (`ID`),
  INDEX `fk_Account_Order1_idx` (`Order_Order_ID` ASC),
  INDEX `fk_Account_Mileage/Coin1_idx` (`Mileage/Coin_Deposit_ID` ASC),
  UNIQUE INDEX `Mileage/Coin_Deposit_ID_UNIQUE` (`Mileage/Coin_Deposit_ID` ASC),
  CONSTRAINT `fk_Account_Order1`
    FOREIGN KEY (`Order_Order_ID`)
    REFERENCES `Dapoba_db`.`Order` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Mileage/Coin1`
    FOREIGN KEY (`Mileage/Coin_Deposit_ID`)
    REFERENCES `Dapoba_db`.`Mileage/Coin` (`Deposit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Dapoba_db`.`Manager` ;

CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Manager` (
  `Manager_ID` CHAR(20) NOT NULL,
  PRIMARY KEY (`Manager_ID`),
  INDEX `fk_Manager_Account1_idx` (`Manager_ID` ASC),
  CONSTRAINT `fk_Manager_Account1`
    FOREIGN KEY (`Manager_ID`)
    REFERENCES `Dapoba_db`.`Account` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
