-- MySQL Script generated by MySQL Workbench
-- 11/27/16 16:15:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Dapoba_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Dapoba_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Dapoba_db` DEFAULT CHARACTER SET utf8 ;
USE `Dapoba_db` ;

-- -----------------------------------------------------
-- Table `Dapoba_db`.`Printer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Printer` (
  `Printer_ID` VARCHAR(20) NOT NULL,
  `Printer_loc` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Printer_ID`),
  UNIQUE INDEX `Printer_ID_UNIQUE` (`Printer_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Cabinet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Cabinet` (
  `cabinet_number` VARCHAR(20) NOT NULL,
  `cabinet_state` VARCHAR(1) NOT NULL,
  `cabinet_password` VARCHAR(8) NULL,
  PRIMARY KEY (`cabinet_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Order` (
  `Order_ID` CHAR(20) NOT NULL,
  `Filename` CHAR(50) NOT NULL,
  `print_place` VARCHAR(2) NOT NULL,
  `page_division` VARCHAR(1) NOT NULL,
  `color` CHAR(20) NOT NULL,
  UNIQUE INDEX `Account_Order_ID_UNIQUE` (`Order_ID` ASC),
  PRIMARY KEY (`Order_ID`),
  UNIQUE INDEX `Filename_UNIQUE` (`Filename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Cash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Cash` (
  `Account_number` VARCHAR(25) NOT NULL,
  `bank_name` CHAR(20) NOT NULL,
  `account_holder_name` CHAR(20) NOT NULL,
  PRIMARY KEY (`Account_number`),
  UNIQUE INDEX `Account_number_UNIQUE` (`Account_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Credit_Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Credit_Card` (
  `Credit_card_number` VARCHAR(12) NOT NULL,
  `Credit_card_password` VARCHAR(4) NOT NULL,
  `ExpDate` DATETIME NOT NULL,
  `Type` CHAR(20) NOT NULL,
  `Balance` VARCHAR(20) NULL DEFAULT NULL,
  UNIQUE INDEX `Credit_card_number_UNIQUE` (`Credit_card_number` ASC),
  PRIMARY KEY (`Credit_card_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Mileage_Coin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Mileage_Coin` (
  `Deposit_ID` VARCHAR(25) NOT NULL,
  `Mileage` VARCHAR(10) NULL DEFAULT NULL,
  `Coin` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Deposit_ID`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `Dapoba_db`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`Account` (
  `ID` CHAR(20) NOT NULL,
  `Name` CHAR(20) NOT NULL,
  `Birth` DATETIME NOT NULL,
  `Email` CHAR(40) NULL DEFAULT NULL,
  `Phone_number` VARCHAR(11) NULL DEFAULT NULL,
  `Password` CHAR(20) NOT NULL,
  `Authority` VARCHAR(1) NOT NULL,
  `Order_ID` VARCHAR(20) NULL DEFAULT NULL,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `E-mail_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Phone_number_UNIQUE` (`Phone_number` ASC),
  UNIQUE INDEX `Order_ID_UNIQUE` (`Order_ID` ASC),
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`History` (
  `Account_ID` CHAR(20) NOT NULL,
  `date` VARCHAR(14) NOT NULL,
  `Coin_history` VARCHAR(11) NULL,
  `Mileage_history` VARCHAR(11) NULL,
  `File_name` CHAR(20) NOT NULL,
  PRIMARY KEY (`Account_ID`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Dapoba_db`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Dapoba_db`.`File` (
  `Filename` CHAR(20) NOT NULL,
  `File_extension` CHAR(20) NOT NULL,
  `File_page_no` VARCHAR(3) NOT NULL,
  `Account_ID` CHAR(20) NOT NULL,
  PRIMARY KEY (`Filename`),
  UNIQUE INDEX `Filename_UNIQUE` (`Filename` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
